apiVersion: apps/v1
kind: Deployment
metadata:
  name: converter-routine
  namespace: ${NAMESPACE}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: converter-routine
  template:
    metadata:
      labels:
        app: converter-routine
    spec:
      containers:
        - name: converter-routine
          image: ${CONVERTER_ROUTINE_IMAGE}
          ports:
            - containerPort: 8080
          env:
            - name: CONVERTER_CATALOGUE_CONNECTION_STRING
              valueFrom:
                configMapKeyRef:
                  name: epos-env
                  key: POSTGRESQL_CONNECTION_STRING
          envFrom:
            - configMapRef:
                name: epos-env
          volumeMounts:
            - name: converter-plugins
              mountPath: /opt/converter/plugins
          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - wget --quiet --tries=1 -O - http://localhost:8080/api/converter-routine/v1/actuator/health \
                  | grep -i 'healthy' || exit 1
            initialDelaySeconds: 10
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 5
          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - wget --quiet --tries=1 -O - http://localhost:8080/api/converter-routine/v1/actuator/health \
                  | grep -i 'healthy' || exit 1
            initialDelaySeconds: 10
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 5
      volumes:
        - name: converter-plugins
          persistentVolumeClaim:
            claimName: converter-plugins
