# dataportal
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: ${NAMESPACE}
  name: dataportal
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: ${DATAPORTAL_DEPLOY_PATH}
spec:
  ingressClassName: ${INGRESS_CLASS}
  rules:
    - http:
        paths:
          - path: ${DATAPORTAL_DEPLOY_PATH}
            pathType: Prefix
            backend:
              service:
                name: dataportal
                port:
                  number: 80
---
# gateway
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: ${NAMESPACE}
  name: gateway
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: ${API_DEPLOY_PATH}
spec:
  ingressClassName: ${INGRESS_CLASS}
  rules:
    - http:
        paths:
          - path: ${API_DEPLOY_PATH}
            pathType: Prefix
            backend:
              service:
                name: gateway
                port:
                  number: 5000
---
# backoffice gui
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: ${NAMESPACE}
  name: backoffice-ui
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: ${BACKOFFICE_DEPLOY_PATH}
spec:
  ingressClassName: ${INGRESS_CLASS}
  rules:
    - http:
        paths:
          - path: ${BACKOFFICE_DEPLOY_PATH}
            pathType: Prefix
            backend:
              service:
                name: backoffice-ui
                port:
                  number: 80
