apiVersion: v1
kind: Service
metadata:
  name: gateway
  namespace: ${NAMESPACE}
spec:
  selector:
    app: gateway
  ports:
    - name: gateway
      port: 5000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: ${NAMESPACE}
  name: gateway
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /${NAMESPACE}/api/v1/
spec:
  ingressClassName: ${INGRESS_CLASS}
  rules:
    - http:
        paths:
          - path: /${NAMESPACE}/api/v1/
            pathType: Prefix
            backend:
              service:
                name: gateway
                port:
                  number: 5000
