services:
  dataportal:
    image: ${DATAPORTAL_IMAGE}
    container_name: ${ENV_NAME}-data-portal
    ports:
      - "${DATAPORTAL_PORT}:80"
    networks:
      - epos_network
    restart: always
    environment:
      - BASE_URL
      - API_HOST
    depends_on:
      - gateway
  gateway:
    image: ${GATEWAY_IMAGE}
    container_name: ${ENV_NAME}-gateway
    ports:
      - "${GATEWAY_PORT}:5000"
    networks:
      - epos_network
    restart: always
    environment:
      - LOAD_RESOURCES_API
      - LOAD_INGESTOR_API
      - LOAD_EXTERNAL_ACCESS_API
      - LOAD_BACKOFFICE_API
      - LOAD_PROCESSING_API
      - LOAD_SHARING_API
      - LOAD_CONVERTER_API
      - LOAD_MONITORING_API
      - LOAD_EMAIL_SENDER_API
      - IS_AAI_ENABLED

      #TODO:check if needed
      - SECURITY_KEY
      - AAI_SERVICE_ENDPOINT
    # depends_on: #TODO

networks:
  epos_network:
