version: "2"

formatters:
  enable:
    - gofumpt
    - goimports
linters:
  default: standard
  enable:
    - staticcheck
    - errcheck
    - gosec
    - misspell
    - dupl
    - goconst
    - gocritic
    - godoclint
    - contextcheck
    - containedctx
    - copyloopvar
  exclusions:
    rules:
      - linters:
          - errcheck
        source: "^\\s*defer\\s+"
      - linters:
          - gosec
        text: "^G204:"
      - linters:
          - gosec
        text: "^G304:"
      - linters:
          - gosec
        text: "^G102:"
      - linters:
          - gosec
        text: "^G107:"
  settings:
    goconst:
      ignore-string-values:
        - "true"
