version: "2"

formatters:
  enable:
    - gofumpt
    - goimports
linters:
  default: standard
  enable:
    - staticcheck
    - errcheck
    - misspell
    - dupl
    - goconst
    - gocritic
    - godoclint
    - contextcheck
    - containedctx
    - copyloopvar
  exclusions:
    rules:
      - linters:
          - errcheck
        source: "^\\s*defer\\s+"
  settings:
    goconst:
      ignore-string-values:
        - "true"
