apiVersion: apps/v1
kind: Deployment
metadata:
  name: metadata-cache
  namespace: ${NAMESPACE}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metadata-cache
  template:
    metadata:
      labels:
        app: metadata-cache
    spec:
      containers:
        - name: metadata-cache
          image: nginx:latest
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: epos-env
            - secretRef:
                name: epos-secret
          volumeMounts:
            - name: ttl-files
              mountPath: /usr/share/nginx/html
          readinessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          livenessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
      volumes:
        - name: ttl-files
          hostPath:
            path: ${TTL_FILES_DIR_PATH}
            type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: metadata-cache
  namespace: ${NAMESPACE}
spec:
  selector:
    app: metadata-cache
  ports:
    - name: metadata-cache
      port: 80
      targetPort: 80
