apiVersion: apps/v1
kind: Deployment
metadata:
  name: dataportal
  namespace: epos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dataportal
  template:
    metadata:
      labels:
        app: dataportal
    spec:
      containers:
        - name: dataportal
          image: epos-ci.brgm.fr:5005/epos/epos-gui/deploy:new-gui-master
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: epos-env
            - secretRef:
                name: epos-secret
          env:
            - name: BASE_URL
              value: /
            - name: API_HOST
              value: http://gateway:5000/api
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 5
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 5
