apiVersion: v1
kind: Service
metadata:
  name: gateway
  namespace: epos
spec:
  selector:
    app: gateway
  ports:
  - name: gateway
    port: 5000
    targetPort: 5000
    nodePort: 32001
  type: NodePort
