apiVersion: v1
kind: Service
metadata:
  name: converter-routine
  namespace: epos
spec:
  selector:
    app: converter-routine
  ports:
  - name: converter-routine
    port: 8080
    targetPort: 8080
