apiVersion: v1
kind: Service
metadata:
  name: metadata-database
  namespace: epos
spec:
  selector:
    app: metadata-database
  ports:
  - name: metadata-database
    port: 5432
    targetPort: 5432
