// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"time"
)

type Docker struct {
	Name       string
	ConfigYaml string
}

type IngestedFile struct {
	EnvironmentName string
	FilePath        string
	IngestedAt      *time.Time
}

type LatestReleaseCache struct {
	ID        int64
	TagName   string
	FetchedAt *time.Time
}
