// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: queries.sql

package sqlc

import (
	"context"
	"time"
)

const deleteDocker = `-- name: DeleteDocker :exec
DELETE FROM
    docker
WHERE
    name = ?
`

func (q *Queries) DeleteDocker(ctx context.Context, name string) error {
	_, err := q.db.ExecContext(ctx, deleteDocker, name)
	return err
}

const deleteIngestedFilesByEnvironment = `-- name: DeleteIngestedFilesByEnvironment :exec
DELETE FROM
    ingested_files
WHERE
    environment_name = ?
`

func (q *Queries) DeleteIngestedFilesByEnvironment(ctx context.Context, environmentName string) error {
	_, err := q.db.ExecContext(ctx, deleteIngestedFilesByEnvironment, environmentName)
	return err
}

const getAllDocker = `-- name: GetAllDocker :many
SELECT
    name,
    config_yaml
FROM
    docker
ORDER BY
    name
`

// Docker queries
func (q *Queries) GetAllDocker(ctx context.Context) ([]Docker, error) {
	rows, err := q.db.QueryContext(ctx, getAllDocker)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Docker
	for rows.Next() {
		var i Docker
		if err := rows.Scan(&i.Name, &i.ConfigYaml); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDockerByName = `-- name: GetDockerByName :one
SELECT
    name,
    config_yaml
FROM
    docker
WHERE
    name = ?
`

func (q *Queries) GetDockerByName(ctx context.Context, name string) (Docker, error) {
	row := q.db.QueryRowContext(ctx, getDockerByName, name)
	var i Docker
	err := row.Scan(&i.Name, &i.ConfigYaml)
	return i, err
}

const getIngestedFilesByEnvironment = `-- name: GetIngestedFilesByEnvironment :many
SELECT
    file_path,
    ingested_at
FROM
    ingested_files
WHERE
    environment_name = ?
ORDER BY
    ingested_at DESC
`

type GetIngestedFilesByEnvironmentRow struct {
	FilePath   string
	IngestedAt *time.Time
}

func (q *Queries) GetIngestedFilesByEnvironment(ctx context.Context, environmentName string) ([]GetIngestedFilesByEnvironmentRow, error) {
	rows, err := q.db.QueryContext(ctx, getIngestedFilesByEnvironment, environmentName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetIngestedFilesByEnvironmentRow
	for rows.Next() {
		var i GetIngestedFilesByEnvironmentRow
		if err := rows.Scan(&i.FilePath, &i.IngestedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLatestReleaseCache = `-- name: GetLatestReleaseCache :one
SELECT
    id, tag_name, fetched_at
FROM
    latest_release_cache
WHERE
    id = 1
`

func (q *Queries) GetLatestReleaseCache(ctx context.Context) (LatestReleaseCache, error) {
	row := q.db.QueryRowContext(ctx, getLatestReleaseCache)
	var i LatestReleaseCache
	err := row.Scan(&i.ID, &i.TagName, &i.FetchedAt)
	return i, err
}

const insertIngestedFile = `-- name: InsertIngestedFile :exec
INSERT INTO
    ingested_files (
        environment_name,
        file_path,
        ingested_at
    )
VALUES
    (?, ?, CURRENT_TIMESTAMP) ON CONFLICT (environment_name, file_path) DO
UPDATE
SET
    ingested_at = CURRENT_TIMESTAMP
`

type InsertIngestedFileParams struct {
	EnvironmentName string
	FilePath        string
}

func (q *Queries) InsertIngestedFile(ctx context.Context, arg InsertIngestedFileParams) error {
	_, err := q.db.ExecContext(ctx, insertIngestedFile, arg.EnvironmentName, arg.FilePath)
	return err
}

const upsertDocker = `-- name: UpsertDocker :one
INSERT INTO
    docker (
        name,
        config_yaml
    )
VALUES
    (?, ?) ON CONFLICT (name) DO
UPDATE
SET
    config_yaml = excluded.config_yaml
RETURNING
    name,
    config_yaml
`

type UpsertDockerParams struct {
	Name       string
	ConfigYaml string
}

func (q *Queries) UpsertDocker(ctx context.Context, arg UpsertDockerParams) (Docker, error) {
	row := q.db.QueryRowContext(ctx, upsertDocker, arg.Name, arg.ConfigYaml)
	var i Docker
	err := row.Scan(&i.Name, &i.ConfigYaml)
	return i, err
}

const upsertLatestReleaseCache = `-- name: UpsertLatestReleaseCache :exec
INSERT INTO
    latest_release_cache (id, tag_name, fetched_at)
VALUES
    (1, ?, ?) ON CONFLICT (id) DO
UPDATE
SET
    tag_name = excluded.tag_name,
    fetched_at = excluded.fetched_at
`

type UpsertLatestReleaseCacheParams struct {
	TagName   string
	FetchedAt *time.Time
}

func (q *Queries) UpsertLatestReleaseCache(ctx context.Context, arg UpsertLatestReleaseCacheParams) error {
	_, err := q.db.ExecContext(ctx, upsertLatestReleaseCache, arg.TagName, arg.FetchedAt)
	return err
}
