apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  namespace: epos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
      - name: gateway
        image: epos-ci.brgm.fr:5005/epos/epos-api-gateway:main
        ports:
        - containerPort: 5000
        envFrom:
        - configMapRef:
            name: epos-env
        - secretRef:
            name: epos-secret
        readinessProbe:
          httpGet:
            path: /api/v1/ui
            port: 5000
          initialDelaySeconds: 10
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 5
        livenessProbe:
          httpGet:
            path: /api/v1/ui
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 5
