apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  namespace: ${NAMESPACE}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: ${GATEWAY_IMAGE}
          ports:
            - containerPort: 5000
          envFrom:
            - configMapRef:
                name: epos-env
            - secretRef:
                name: epos-secret
          readinessProbe:
            httpGet:
              path: ${API_PATH}/ui
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 5
          livenessProbe:
            httpGet:
              path: ${API_PATH}/ui
              port: 5000
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 5
