apiVersion: v1
kind: Secret
metadata:
  name: epos-secret
  namespace: ${NAMESPACE}
type: Opaque
stringData:
  BROKER_PASSWORD: ${RABBITMQ_PASSWORD}
  POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  SECURITY_KEY: ${SECURITY_KEY}
  MONITORING_PWD: ${MONITORING_PWD}
