apiVersion: v1
kind: Service
metadata:
  name: converter-service
  namespace: epos
spec:
  selector:
    app: converter-service
  ports:
  - name: converter-service
    port: 8080
    targetPort: 8080
