apiVersion: v1
kind: Service
metadata:
  name: dataportal
  namespace: ${NAMESPACE}
spec:
  selector:
    app: dataportal
  ports:
    - name: dataportal
      port: 80
      targetPort: 80
      nodePort: ${DATAPORTAL_PORT}
  type: NodePort
