apiVersion: v1
kind: Service
metadata:
  name: gateway
  namespace: ${NAMESPACE}
spec:
  selector:
    app: gateway
  ports:
    - name: gateway
      port: 5000
      targetPort: 5000
      nodePort: ${GATEWAY_PORT}
  type: NodePort
