// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

type Docker struct {
	Name          string
	Directory     string
	ApiUrl        string
	GuiUrl        string
	BackofficeUrl string
}

type Kubernetes struct {
	Name          string
	Directory     string
	Context       string
	ApiUrl        string
	GuiUrl        string
	BackofficeUrl string
	Protocol      string
}
