package common

import (
	"fmt"
	"runtime/debug"
	"time"
)

var Version = "dev"

// GetVersion returns the version of the CLI
func GetVersion() string {
	if Version != "" && Version != "dev" {
		return Version
	}

	if info, ok := debug.ReadBuildInfo(); ok && info.Main.Version != "(devel)" {
		return info.Main.Version
	}
	return "dev"
}

// GenerateExportHeader returns a standardized header for exported files
func GenerateExportHeader(doNotEdit bool) string {
	output := fmt.Sprintf("# Generated by EPOS open-source CLI\n# Version: %s\n# Timestamp: %s\n",
		GetVersion(),
		time.Now().UTC().Format(time.RFC3339))
	if doNotEdit {
		output = fmt.Sprintf("%s# DO NOT EDIT\n", output)
	}
	return fmt.Sprintf("%s\n", output)
}
